-- 딜 워치리스트(관심 딜/찜) — 사용자가 시장 피드 카드를 저장해 모아본다. 무료(퍼널).
-- 테넌트 스코프(다른 테넌트 데이터 격리). 카드가 purge 돼도 살아남도록 표시 필드를 비정규화 저장.
-- DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE deal_watch (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    feed_item_id  BIGINT NOT NULL,                 -- 원본 카드 id(중복 방지 키)
    title         VARCHAR(300) NOT NULL,
    summary       VARCHAR(1000),
    asset_type    VARCHAR(20),
    location      VARCHAR(120),
    source_text   VARCHAR(4000),                   -- '이 딜 분석하기' 재진입 시드
    source_url    VARCHAR(500),
    created_at    TIMESTAMP NOT NULL
);
-- 한 사용자가 같은 카드를 중복 찜하지 못하게.
CREATE UNIQUE INDEX ux_deal_watch_user_item ON deal_watch (tenant_id, owner_user_id, feed_item_id);
CREATE INDEX ix_deal_watch_owner ON deal_watch (tenant_id, owner_user_id, id);
