-- 크레딧 충전 결제(토스페이먼츠) — 일회성 충전. 테넌트 스코프.
-- 주문 생성 시 PENDING(금액·크레딧은 서버 팩 기준), 토스 서버 승인검증 성공 시 CONFIRMED + 크레딧 지급.
-- order_id 유니크 → 멱등·중복충전 차단. DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE payment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    order_id      VARCHAR(64) NOT NULL,            -- 우리가 생성한 주문번호(토스 orderId)
    pack_id       VARCHAR(30) NOT NULL,            -- CreditPack enum 이름
    credits       INTEGER NOT NULL,               -- 충전 크레딧(서버 팩 권위)
    amount_krw    INTEGER NOT NULL,               -- 결제 금액(서버 팩 권위)
    status        VARCHAR(20) NOT NULL,            -- PENDING/CONFIRMED/FAILED/CANCELED
    payment_key   VARCHAR(200),                   -- 토스 결제키(승인 후)
    method        VARCHAR(30),                    -- 결제수단(카드 등)
    approved_at   TIMESTAMP,
    created_at    TIMESTAMP NOT NULL
);
-- 멱등·중복충전 방지의 핵심 유니크 키.
CREATE UNIQUE INDEX ux_payment_order_id ON payment (order_id);
CREATE INDEX ix_payment_owner ON payment (tenant_id, owner_user_id, id);
