-- 리드(비회원) 캡처 — 무료 ProForma 엑셀 계산기 등 공개 도구에서 이메일 수집.
-- 가입 전(계정·테넌트 없음) 단계라 테넌트 비스코프(news_subscriber 와 동일 정책).
-- marketing_opt_in=TRUE 인 리드만 마케팅 메일 대상. source 로 유입 도구 구분.
-- DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE lead (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(200) NOT NULL,
    source             VARCHAR(60)  NOT NULL,          -- 유입 도구(예: FREE_PROFORMA)
    marketing_opt_in   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP    NOT NULL
);
CREATE INDEX ix_lead_email ON lead (email);
CREATE INDEX ix_lead_source ON lead (source);
