-- 자산관리(PM) - 임대차 관리. AM 위탁 건물의 임대차 계약을 저장·집계하고 만기/인상 리마인더를 발송한다.
-- 테넌트 스코프(다른 테넌트 데이터 격리, IDOR 차단). 상태(ACTIVE/UPCOMING/EXPIRED)는 저장하지 않고
-- 조회 시 날짜로 파생 계산한다(시간 경과로 상태가 낡지 않게).
-- DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE building (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    name          VARCHAR(200) NOT NULL,
    address       VARCHAR(300),
    asset_type    VARCHAR(20),                     -- 오피스 | 물류 | 호텔 | 리테일
    gfa_pyeong    DOUBLE PRECISION,                -- 연면적(평)
    notes         VARCHAR(1000),
    created_at    TIMESTAMP NOT NULL
);
CREATE INDEX ix_building_owner ON building (tenant_id, owner_user_id, id);

CREATE TABLE lease (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT NOT NULL,
    owner_user_id        BIGINT NOT NULL,
    building_id          BIGINT NOT NULL,
    tenant_name          VARCHAR(200) NOT NULL,    -- 임차인명
    unit_label           VARCHAR(100),             -- 층/호(예: '10F', '지하1층')
    area_pyeong          DOUBLE PRECISION,         -- 임대면적(평)
    monthly_rent_manwon  DOUBLE PRECISION,         -- 월 임대료(만원)
    deposit_manwon       DOUBLE PRECISION,         -- 보증금(만원)
    mgmt_fee_manwon      DOUBLE PRECISION,         -- 월 관리비(만원)
    lease_start_date     DATE,
    lease_end_date       DATE,
    rent_free_months     INTEGER,                  -- 렌트프리(개월)
    escalation_pct       DOUBLE PRECISION,         -- 임대료 인상률(%)
    next_escalation_date DATE,                     -- 다음 인상 예정일
    source_text          VARCHAR(8000),            -- 원문 계약서(추출 근거)
    notes                VARCHAR(1000),
    created_at           TIMESTAMP NOT NULL
);
CREATE INDEX ix_lease_owner ON lease (tenant_id, owner_user_id, id);
CREATE INDEX ix_lease_building ON lease (building_id);

-- 리마인더 이메일 발송 로그 - (임대차·이벤트·기준일) 단위 멱등(중복 발송 방지).
CREATE TABLE lease_reminder_sent (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    lease_id      BIGINT NOT NULL,
    event_type    VARCHAR(20) NOT NULL,            -- EXPIRY | ESCALATION | RENT_FREE_END
    due_date      DATE NOT NULL,
    sent_at       TIMESTAMP NOT NULL,
    created_at    TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ux_lease_reminder_dedupe ON lease_reminder_sent (lease_id, event_type, due_date);
