-- 업계 헤드라인 보드 — 자산운용사가 주로 보는 CRE 매체(SPI·딜사이트·코어비트) 제목만 집계.
-- 딜 카드(market_feed_item)와 완전 분리: 제목+출처+발행시각만 보관, 클릭 시 원문으로 이동.
-- 글로벌 콘텐츠(테넌트 비스코프). 읽기=인증 사용자. 수집=기존 인제스트에 얹힘(구글뉴스 site: 검색).
-- DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE headline_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(300)  NOT NULL,
    source       VARCHAR(40)   NOT NULL,        -- 매체 라벨: SPI | 딜사이트 | 코어비트
    source_url   VARCHAR(500),                  -- 원문 링크(클릭 시 이동)
    published_at TIMESTAMP,
    dedup_key    VARCHAR(300),                  -- 정규화 링크 — 재수집 시 중복 삽입 차단
    created_at   TIMESTAMP     NOT NULL
);
CREATE INDEX ix_headline_published ON headline_item (published_at);
CREATE INDEX ix_headline_dedup ON headline_item (dedup_key);
