-- aixnative — Phase 1 foundation schema.
-- DB-agnostic: no Oracle-specific syntax (no SEQ.NEXTVAL / ROWNUM / SYSDATE / MERGE).
-- PK uses identity columns supported by both PostgreSQL 10+ and H2 (test).
-- Every domain table carries tenant_id day-one for multi-tenant isolation.

CREATE TABLE tenants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT       NOT NULL,
    email          VARCHAR(320) NOT NULL,
    password_hash  VARCHAR(100),               -- null for social-only accounts
    status         VARCHAR(20)  NOT NULL,       -- ACTIVE / DISABLED
    plan           VARCHAR(20)  NOT NULL,       -- FREE / PAID
    auth_provider  VARCHAR(20)  NOT NULL,       -- LOCAL / GOOGLE / KAKAO
    email_verified BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL
);

CREATE UNIQUE INDEX ux_users_email ON users (email);
CREATE INDEX ix_users_tenant ON users (tenant_id);

-- Append-only credit ledger. Balance = SUM(delta) for the tenant/user.
-- Free signup grant (+N), AI analysis debit (-1), later purchase top-up (+M).
CREATE TABLE credit_ledger (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    delta       INTEGER     NOT NULL,
    reason      VARCHAR(40) NOT NULL,           -- SIGNUP_GRANT / AI_ANALYSIS / PURCHASE
    created_at  TIMESTAMP   NOT NULL
);

CREATE INDEX ix_credit_ledger_tenant_user ON credit_ledger (tenant_id, user_id);

-- AI analysis run history (soft-deletable), scoped to tenant.
CREATE TABLE ai_tool_run (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL,
    owner_user_id BIGINT      NOT NULL,
    tool          VARCHAR(60) NOT NULL,
    status        VARCHAR(20) NOT NULL,         -- SUCCESS / FAILED
    request_hash  VARCHAR(64),
    result_ref    VARCHAR(200),
    created_at    TIMESTAMP   NOT NULL,
    deleted_at    TIMESTAMP
);

CREATE INDEX ix_ai_tool_run_tenant_owner ON ai_tool_run (tenant_id, owner_user_id);
CREATE INDEX ix_ai_tool_run_deleted ON ai_tool_run (deleted_at);
