-- 경량 행동 이벤트 로그. 방문·무료계산·분석시작 등 퍼널/이탈 지점 파악용.
-- 익명 방문자도 기록하므로 tenant_id·user_id 는 nullable. 과금(ai_tool_run)과 별개의 얕은 신호.
CREATE TABLE user_event (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT,
    user_id    BIGINT,
    event      VARCHAR(40)  NOT NULL,   -- page_view / free_calc / analysis_start ...
    path       VARCHAR(200),            -- 발생 화면(메뉴 키 등)
    meta       VARCHAR(500),            -- 부가 정보(짧은 문자열, 선택)
    created_at TIMESTAMP    NOT NULL
);
CREATE INDEX ix_user_event_event_created ON user_event (event, created_at);
CREATE INDEX ix_user_event_created       ON user_event (created_at);
CREATE INDEX ix_user_event_user          ON user_event (user_id);
