-- 공감랭킹 소셜 자동게시 - 생성된 게시물(글로벌 콘텐츠, 비테넌트).
-- PostgreSQL / H2 공통 구문만 사용(DB-agnostic). 이미지는 방언 차이(BYTEA vs BLOB) 회피를 위해
-- base64 TEXT 로 보관(MVP). 규모 커지면 GCS 오브젝트 스토리지로 이전.
CREATE TABLE social_post (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic            VARCHAR(80)  NOT NULL,   -- 주제/카테고리: 부동산·재테크·범용 등
    title            VARCHAR(300) NOT NULL,   -- 카드 대표 제목("이번 주 부동산 화제 TOP 5")
    caption_text     TEXT,                    -- 플랫폼 캡션(본문)
    slides_json      TEXT,                    -- 랭킹 슬라이드 배열 JSON [{rank,title,summary,sourceName,sourceUrl}]
    hashtags         VARCHAR(500),            -- 해시태그(공백 구분)
    media_type       VARCHAR(20)  NOT NULL,   -- IMAGE | VIDEO
    platform         VARCHAR(20)  NOT NULL,   -- INSTAGRAM | YOUTUBE
    status           VARCHAR(20)  NOT NULL,   -- DRAFT | PENDING | APPROVED | PUBLISHED | REJECTED
    image_base64     TEXT,                    -- 렌더된 카드 이미지(PNG) base64. 공개 엔드포인트에서 디코드 스트리밍
    source_refs_json TEXT,                    -- 출처 근거 JSON [{name,url}] (저작권 근거)
    ai_provider      VARCHAR(40),             -- 캡션 생성 제공자("Claude")
    origin           VARCHAR(60),             -- 생성 경로("AUTO" | "ADMIN")
    dedup_key        VARCHAR(400),            -- 중복 차단 키(주제+날짜 등)
    published_at     TIMESTAMP,               -- 실제 게시 시각
    external_post_id VARCHAR(120),            -- 게시 후 플랫폼 게시물 ID
    error            VARCHAR(1000),           -- 마지막 실패 사유(게시 등)
    created_at       TIMESTAMP    NOT NULL
);

CREATE INDEX ix_social_post_status ON social_post (status);
CREATE INDEX ix_social_post_dedup_key ON social_post (dedup_key);
CREATE INDEX ix_social_post_created_at ON social_post (created_at);
