-- 동네 리포트 AI 브리핑(크레딧 과금) 저장 - 사용자별 마이페이지 조회용. 테넌트 스코프.
-- PostgreSQL / H2 공통 구문만(DB-agnostic).
CREATE TABLE residential_brief (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL,   -- 테넌트(격리)
    owner_user_id BIGINT       NOT NULL,   -- 소유 사용자
    query         VARCHAR(300) NOT NULL,   -- 분석한 주소/지역
    region        VARCHAR(40),             -- 시도(서울·경기 등)
    brief_text    TEXT         NOT NULL,   -- Claude 생성 브리핑 본문
    created_at    TIMESTAMP    NOT NULL
);

CREATE INDEX ix_residential_brief_owner ON residential_brief (tenant_id, owner_user_id, id DESC);
