-- 이메일 인증 토큰. 가입 시 발급(메일 링크) → 클릭 시 소비.
-- 소비 시 users.email_verified=true + 무료 크레딧 1회 지급(어뷰징 방어).
-- DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE email_verification_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    token       VARCHAR(64)  NOT NULL UNIQUE,   -- ux_evt_token (URL-safe base64, 32바이트)
    expires_at  TIMESTAMP    NOT NULL,
    consumed_at TIMESTAMP,                       -- null = 미사용
    created_at  TIMESTAMP    NOT NULL
);
CREATE INDEX ix_evt_user ON email_verification_token (user_id);
