-- 시장 인텔리전스 피드 — 큐레이션된 거래/시장 다이제스트(홍보·인게이지먼트).
-- 글로벌 콘텐츠(테넌트 비스코프). 읽기=인증 사용자, 쓰기=ADMIN.
-- source_text 는 '이 딜 분석하기' 시 딜 추출(extract-deal)로 넘기는 원문.
-- DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE market_feed_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200)  NOT NULL,
    summary      VARCHAR(1000),
    asset_type   VARCHAR(20),                  -- 오피스 | 물류 | 호텔 | 리테일 | null
    location     VARCHAR(120),
    source_text  VARCHAR(4000),                -- 분석 진입용 딜 원문(기사 요약 등)
    source_url   VARCHAR(500),
    published_at TIMESTAMP,
    created_at   TIMESTAMP     NOT NULL
);
CREATE INDEX ix_mfi_published ON market_feed_item (published_at);
