-- 비밀번호 재설정 토큰. '비밀번호 찾기' → 가입 이메일로 링크 발송 → 클릭 시 새 비번 설정.
-- 1회용·단기 만료. DB-agnostic (PostgreSQL·H2).

CREATE TABLE password_reset_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    token       VARCHAR(64)  NOT NULL UNIQUE,   -- ux_prt_token
    expires_at  TIMESTAMP    NOT NULL,
    consumed_at TIMESTAMP,                       -- null = 미사용
    created_at  TIMESTAMP    NOT NULL
);
CREATE INDEX ix_prt_user ON password_reset_token (user_id);
