-- 마켓 브리핑 — 무료 AI(Mistral)가 수집 기사 풀을 합성한 일일 시장 다이제스트.
-- 뉴스레터 강점 이식: 헤드라인·전망·토픽섹션·워치리스트·리스크. 매 수집마다 새 행(최신 1건 노출).
-- 글로벌 콘텐츠(테넌트 비스코프). DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE market_briefing (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    briefing_date  DATE          NOT NULL,
    headline       VARCHAR(500),
    outlook        TEXT,                    -- 단기 시장 전망(서술)
    sections_json  TEXT,                    -- [{topic,summary,impact}]
    watchlist_json TEXT,                    -- [{item,why}]
    risks_json     TEXT,                    -- [{signal,severity,mitigation}] severity=LOW|MEDIUM|HIGH
    article_count  INTEGER,
    ai_provider    VARCHAR(40),
    generated_at   TIMESTAMP     NOT NULL
);
CREATE INDEX ix_mb_generated ON market_briefing (generated_at);
