-- 시장 브리핑 메일 구독자(무료). 재방문 유도용 — 매일 아침 브리핑을 메일로 받는다.
-- 글로벌(테넌트 비스코프). 구독은 로그인 사용자가 본인 이메일로, 해지는 메일 푸터 토큰 링크.
-- DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE news_subscriber (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(200) NOT NULL UNIQUE,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    unsub_token VARCHAR(64)  NOT NULL,          -- 메일 1클릭 해지 토큰
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP
);
CREATE INDEX ix_news_sub_active ON news_subscriber (active);
