-- 뉴스레터 발송 로그 — "누구한테 언제 보냈는지" 관리자 추적용. 발송 1건 = 1행.
-- 글로벌(테넌트 비스코프). DB-agnostic: PostgreSQL·H2 공통 구문만 사용.

CREATE TABLE newsletter_send_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(200) NOT NULL,
    subject     VARCHAR(300),
    status      VARCHAR(20)  NOT NULL,        -- SENT | FAILED
    briefing_id BIGINT,                        -- 어떤 브리핑을 보냈는지(참조)
    sent_at     TIMESTAMP    NOT NULL
);
CREATE INDEX ix_nsl_sent ON newsletter_send_log (sent_at);
